#!/bin/sh
# splash -- customize splash screens
# Copyright (C) 2021  Jacob Koziej <jacobkoziej@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -eou pipefail

SYS_DIR="/usr/share/remarkable"
CONF_DIR="${REMARKABLE_UTILS_DOTDIR:="$HOME/.remarkable-utils"}/splash"
BACKUP_DIR="$CONF_DIR/backup"

backup() {
	cp -a "$SYS_DIR"/*.png -t "$BACKUP_DIR"
}

restore() {
	cp -a -f "$BACKUP_DIR"/*.png -t "$SYS_DIR"
}

if [ ! -d "$BACKUP_DIR" ]; then
	printf 'No backup found, creating a backup...'
	mkdir -p "$BACKUP_DIR"
	backup
	echo 'OK'
fi

for arg in "$@"; do
	case $arg in
	-r | --restore)
		printf 'Restoring splash screens from backup...'
		restore
		echo 'OK'
		exit
		;;
	esac
done
