#!/bin/sh
# splash -- customize splash screens
# Copyright (C) 2021  Jacob Koziej <jacobkoziej@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -eou pipefail

REMARKABLE_UTILS_VERSION='@REMARKABLE_UTILS_VERSION@'
SPLASH_VERSION='0.1.0'

SYS_DIR='/usr/share/remarkable'
CONF_DIR="${REMARKABLE_UTILS_DOTDIR:="$HOME/.remarkable-utils"}/splash"
BACKUP_DIR="$CONF_DIR/backup"

backup() {
	cp -a "$SYS_DIR"/*.png "$BACKUP_DIR"
}

copyright() {
	head -n 16 "$0" | tail -n +2 - | cut -c3- -
}

info() {
	head -n 4 "$0" | tail -n +2 - | cut -c3- -
	cat <<EOF
This program is bundled as a part of \`remarkable-utils'
upstream: <git.jacobkoziej.xyz/remarkable-utils>
remarkable-utils version: $REMARKABLE_UTILS_VERSION
splash version: $SPLASH_VERSION

This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see \`-c' for details.
EOF
}

restore() {
	for splash in "$BACKUP_DIR"/*.png; do
		splash="${splash##*/}"
		printf '%s...' "$splash"

		if cmp -s "$BACKUP_DIR/$splash" "$SYS_DIR/$splash"; then
			echo 'SKIPPING'
			continue
		fi

		cp -a -f "$BACKUP_DIR/$splash" "$SYS_DIR"
		echo 'OK'
	done
}

write() {
	for splash in "$CONF_DIR"/*.png; do
		splash="${splash##*/}"
		printf '%s...' "$splash"

		if [ ! -f "$BACKUP_DIR/$splash" ]; then
			echo 'NOT FOUND'
			continue
		fi

		if cmp -s "$CONF_DIR/$splash" "$SYS_DIR/$splash"; then
			echo 'SKIPPING'
			continue
		fi

		cp -a -f "$CONF_DIR/$splash" "$SYS_DIR"
		echo 'OK'
	done
}

if [ ! -d "$BACKUP_DIR" ]; then
	printf 'No backup found, creating a backup...'
	mkdir -p "$BACKUP_DIR"
	backup
	echo 'OK'
fi

for arg in "$@"; do
	case $arg in
	-c | --copyright)
		copyright
		exit
		;;
	-i | --info)
		info
		exit
		;;
	-r | --restore)
		echo 'Restoring splash screens from backup...'
		restore
		echo 'DONE'
		exit
		;;
	-w | --write)
		echo 'Writing custom splash screens...'
		write
		echo 'DONE'
		exit
		;;
	esac
done
